import {Center} from 'native-base';
import {StyleSheet} from 'react-native';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';
import {AppColor, fontFamily, colors} from '../../../globals/utilities';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },

  headerView: {
    flexDirection: 'row',
    paddingTop: responsiveHeight(3),
    marginLeft: responsiveWidth(5),
  },
  heading: {
    fontSize: responsiveFontSize(3),
    color: 'black',
    fontWeight: '700',
    textAlign: 'center',
    //paddingTop: responsiveHeight(3),
  },
  label: {
    fontSize: responsiveFontSize(2),
    color: colors.gray600,
    fontFamily: fontFamily.appTextBold,
    paddingTop: responsiveHeight(3),
    marginLeft: responsiveWidth(6),
  },
  startTimeButtons: {
    fontFamily: fontFamily.appTextRegular,
    fontSize: responsiveFontSize(1.8),
    width: responsiveWidth(90),
    height: responsiveHeight(6.5),
    borderWidth: 1,
    borderRadius: responsiveWidth(2),
    textAlign: 'left',
    justifyContent: 'center',
    marginLeft: responsiveWidth(5),
  },
  text: {
    fontSize: responsiveFontSize(2),
    color: colors.gray600,
    fontFamily: fontFamily.appTextBold,
    textAlign: 'center',
  },
  inputContainer: {
    width: responsiveWidth(90),
    alignSelf: 'center',
    justifyContent: 'space-evenly',
    //marginTop: responsiveHeight(1),
  },
  input: {
    width: responsiveWidth(90),
    height: responsiveHeight(6),
    borderWidth: 1,
    borderColor: AppColor.primary,
    borderRadius: responsiveWidth(2),
    paddingLeft: responsiveWidth(4),
    color: 'black',
  },
  labelText: {
    fontSize: responsiveFontSize(2),
    color: AppColor.text,
    fontWeight: '500',
    paddingVertical: responsiveHeight(1),
  },
  bottonTabContainer: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: responsiveWidth(100),
    justifyContent: 'space-between',
    paddingVertical: responsiveHeight(0.6),
    paddingBottom:20,
    paddingHorizontal: responsiveWidth(6),
  },
  tabIconButton: {
    alignItems: 'center',
    paddingVertical: responsiveHeight(0.5),
  },
  tabIconImage: {
    resizeMode: 'contain',
    height: responsiveHeight(4.5),
    width: responsiveWidth(7.5),
  },
  tabButtonText: {
    fontSize: responsiveFontSize(1.6),
    color: colors.gray600,
    fontFamily: fontFamily.appTextBold,
    paddingTop: responsiveHeight(0.5),
  },
  orangeText: {
    color: AppColor.primary,
  },
  indicatorView: {
    borderRadius: responsiveWidth(7 / 2),
    height: responsiveWidth(7),
    width: responsiveWidth(7),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: AppColor.primary,
  },
  modalView: {
    backgroundColor: 'white',
    width: responsiveWidth(90),
    height: responsiveHeight(60),
    alignSelf: 'center',
    alignItems: 'center',
    borderRadius: responsiveWidth(2),
  },
  modalHeading: {
    fontSize: responsiveFontSize(2),
    color: colors.gray600,
    fontFamily: fontFamily.appTextExtraBold,
    fontSize: responsiveFontSize(4),
    paddingVertical: responsiveHeight(1),
    marginTop: responsiveHeight(3),
  },
  modalOKButtons: {
    fontFamily: fontFamily.appTextRegular,
    fontSize: responsiveFontSize(1.8),
    width: responsiveWidth(80),
    height: responsiveHeight(6.5),
    borderRadius: responsiveWidth(2),
    textAlign: 'left',
    justifyContent: 'center',
    marginTop: responsiveHeight(5),
    backgroundColor: AppColor.primary,
  },
  modalCancelButtons: {
    fontFamily: fontFamily.appTextRegular,
    fontSize: responsiveFontSize(1.8),
    width: responsiveWidth(80),
    height: responsiveHeight(6.5),
    borderWidth: 1,
    borderRadius: responsiveWidth(2),
    textAlign: 'left',
    justifyContent: 'center',
    marginTop: 6,
  },
  timePicker: {
    backgroundColor: 'transparent',
    width: responsiveWidth(70),
    alignSelf: 'center',
    height: responsiveHeight(20),
  },
});
export default styles;
